### ISSUE TITLE
Cadastro de Produtos

### ISSUE THREAD

**Issue by Daniel-Nascimento-Em** [danieldrn/cm#1]
@thiago2608santana

**Comment by Daniel-Nascimento-Em** [comment]
@CelsoGomesEM Ajuda ai Celso

**Comment by CelsoGomesEM** [comment]
Quero cargo de gerência do projeto.

**Comment by Daniel-Nascimento-Em** [comment]
> <#CD1HJ54PP|desenvolvimento> 2219
<sub>[View in Slack](https://escolarmanager.slack.com/archives/DD1J7EF1T/p1537968912000100)</sub>
